import { create } from "zustand";
import type { DraftWindow } from "../engine/saveGame";
import type { DraftPickRecord } from "../engine/draft";
import type { RatedAttribute } from "../types/player";

interface DraftState {
  /** Null until the coach starts this year's National Draft, or hydrated from a loaded save that already had one in progress — see DraftWindow's own doc comment for why this is a real "started or not" flag rather than a lazily-materialising window like Contracts/Trade. */
  window: DraftWindow | null;

  /** Opens a brand-new draft night wholesale — the pool/order are generated by the caller (see useSaveStore.ts's `startDraft`), this store just holds the result. */
  openWindow: (window: DraftWindow) => void;
  /** Appends one completed pick and advances `currentPickIndex` by one. No-op if no window is open. */
  logPick: (record: DraftPickRecord) => void;
  /** Spends one unit of the shared scouting budget to reveal `attribute` on `prospectId`. No-op if the budget is empty, the attribute's already revealed for that prospect, or no window is open. */
  revealAttribute: (prospectId: number, attribute: RatedAttribute) => void;
  /** Back to no draft in progress — a new off-season year starts fresh, see useSaveStore.ts's `runOffSeason`. Also used once the draft finishes and the coach moves on. */
  clearWindow: () => void;
  /** Bulk-replaces the window — used to hydrate from a loaded save, see useSaveStore.ts. */
  restoreWindow: (window: DraftWindow | null) => void;
}

/**
 * National Draft window state — see src/engine/draft.ts. A separate store
 * from useSaveStore, matching this project's established one-store-per-
 * concern pattern (useContractStore for Contracts, useTradeStore for Trade
 * Period) — this one just owns `DraftWindow`'s pool/order/picks/scouting
 * state.
 *
 * Deliberately does NOT touch the live player pool itself (no `loadPool`
 * calls here) — every other concern-store follows the same rule. Drafted
 * prospects are spliced into `ALL_PLAYERS` by useSaveStore.ts's
 * `confirmDraftPick`/`autoResolveNextPick`/`finishDraft`, which call this
 * store's `logPick` afterwards, mirroring exactly how Trade Period's
 * `confirmTrade` calls `useTradeStore.logEntry`.
 */
export const useDraftStore = create<DraftState>((set) => ({
  window: null,

  openWindow: (window) => set({ window }),

  logPick: (record) =>
    set((state) => {
      if (!state.window) return state;
      return { window: { ...state.window, picks: [...state.window.picks, record], currentPickIndex: state.window.currentPickIndex + 1 } };
    }),

  revealAttribute: (prospectId, attribute) =>
    set((state) => {
      const w = state.window;
      if (!w || w.scoutingBudgetRemaining <= 0) return state;
      const already = w.revealed[prospectId] ?? [];
      if (already.includes(attribute)) return state;
      return {
        window: {
          ...w,
          scoutingBudgetRemaining: w.scoutingBudgetRemaining - 1,
          revealed: { ...w.revealed, [prospectId]: [...already, attribute] },
        },
      };
    }),

  clearWindow: () => set({ window: null }),

  restoreWindow: (window) => set({ window }),
}));
