import { anyLines, byStatus, clubLines, p, type Phrase } from "./types";

/** Welcome screen's missed-calls feed. Speaker: a club president, voicemail length. */
export const missedCall: Phrase[] = [
  ...anyLines("missedCall", [
    "Your pressure numbers were ridiculous. Call me back, {coachFirst}.",
    "Watched your state league final three times. Ring me.",
    "I've got a list, a board and a blank cheque. Missing piece is you.",
    "Whatever the others are offering, we'll talk. Pick up, {coachFirst}.",
  ]),
  ...byStatus("missedCall", "contender", [
    "The list is ready now. Not next year. Now.",
    "We finished {finish}. You're the last one per cent.",
    "One coach away from a flag. We think it's you.",
    "Nobody reads a stoppage like you do. Bring that to a top-four side.",
    "Short deal, big stakes, best list you'll ever get. Call me.",
    "{star} asked about you by name this morning.",
    "Premierships don't wait. Neither should you, {coachFirst}.",
    "We don't need a rebuild. We need your ball movement.",
  ], "hungry"),
  ...byStatus("missedCall", "rising", [
    "Our kids play the way you coach. Fast. Call me.",
    "We jumped to {finish}. Picture what you'd do with this group.",
    "Young list, big engine, nobody to steer it. That's your job.",
    "The trend line only goes one way here. Get on it early.",
    "{topYoungster} is going to be a star. He needs your system.",
    "Everything's pointing up at the {nick}. Come and point it higher.",
    "Your transition numbers and our legs. Think about it.",
    "Finals are close. You'd get us there sooner.",
  ], "warm"),
  ...byStatus("missedCall", "middle", [
    "Eighth to fourteenth for too long. You're how we break out.",
    "Good list, no identity. You'd give it one inside a pre-season.",
    "We keep finishing around {finish}. That stops with you.",
    "Plenty of talent here, {coachFirst}. Just needs a plan.",
    "The board wants September. I want you to deliver it.",
    "Stuck in neutral. Your game plan is the gear change.",
    "Ring me before the other clubs do. Please.",
    "You turned a nothing side into champions once. Do it again here.",
  ], "measured"),
  ...byStatus("missedCall", "sleepingGiant", [
    "Biggest members base in the state and nothing to show for it. Fix it.",
    "Wake this place up, {coachFirst}. The members are desperate.",
    "Sixty thousand people want to believe again. Give them a reason.",
    "Big club, bad habits. You're the circuit breaker.",
    "History says we're a power. The ladder says {finish}. Help me.",
    "It's the biggest job in footy and it's yours if you want it.",
    "We've got the money and the members. We need the mind.",
    "Nobody bold has coached here in years. Be bold.",
  ], "desperate"),
  ...byStatus("missedCall", "reset", [
    "We slipped to {finish}. The list's better than that. So are you.",
    "It's a reset, not a rebuild. You'd turn it in one pre-season.",
    "Good players, wrong system. Call me back.",
    "We lost our way last year. You're the compass.",
    "Nobody here wants to wait five years. Neither do you.",
    "Two bad seasons don't make a bad club. Come prove it.",
    "Real list, real money, real impatience. Ring me.",
    "Your data on repeat stoppages had our whole footy department talking.",
  ], "blunt"),
  ...byStatus("missedCall", "rebuild", [
    "Five-year deal on the table. Full control of list management.",
    "Only one way from {finish}, and it's up. Come take us there.",
    "Kids, draft picks, patience. And you, hopefully.",
    "{topYoungster} needs a coach who believes in him. Call me.",
    "No pressure for two years. Just build us something that lasts.",
    "Fresh start, blank whiteboard. Your kind of job.",
    "We'll give you time. We won't give you excuses. Call me.",
    "The last rebuild took a decade. You'd do it in three.",
  ], "warm"),
  ...[
    p("missedCall.interstate.01", "The weather's better, the house is paid for, and the list is ready. Think about it.", { isInterstate: true }),
    p("missedCall.interstate.02", "We'll fly the family over first class. Just take the meeting.", { isInterstate: true }),
    p("missedCall.interstate.03", "Different state, same obsession. The {nick} faithful would love you.", { isInterstate: true }),
    p("missedCall.interstate.04", "Everyone warns you about the travel. Nobody mentions the home-ground advantage.", { isInterstate: true }),
    p("missedCall.oldstar.01", "{star} has two good years left. Make them count.", { starAgeMin: 30 }),
    p("missedCall.oldstar.02", "Our best player is {star}, and his window is closing. Open it back up.", { starAgeMin: 30 }),
    p("missedCall.kidstar.01", "{star} is our best player already, and he's barely started. Imagine him under you.", { starAgeMax: 22 }),
    p("missedCall.kidstar.02", "Build the whole thing around {star}. He's that good.", { starAgeMax: 22 }),
  ],
  ...clubLines("missedCall", {
    ADEL: ["Showdown week is the best week in footy. Come and coach one.", "Navy, red and gold. Two flags in our history, a third with you."],
    BL: ["Back-to-back and we want more. The Gabba is waiting.", "Three-peat heritage. We think you could start another one."],
    CARL: ["Sixteen flags and none since '95. That drought needs a coach like you.", "Navy blue, big crowds, zero patience. Call me."],
    COLL: ["It's Collingwood, {coachFirst}. You don't say no to Collingwood.", "Black and white forever. Come make the next flag yours."],
    ESS: ["Name your price. We'll clear the box by Friday.", "Windy Hill still talks about you. Come make it official."],
    FRE: ["No flag yet. Be the coach who changes that.", "Purple haze at Optus, every week. Come see it."],
    GEEL: ["We don't rebuild. We reload. Help us reload.", "The Cattery hasn't missed you yet. Don't make it wait."],
    GCFC: ["We just won our first final. Now we want the second.", "Sunshine, a young list and no traffic. Call me."],
    GWS: ["Western Sydney is ready for a flag. Are you?", "Orange army, young core, big ambition. Pick up."],
    HAW: ["This club builds dynasties. Build us the next one.", "Brown and gold, family club. We'd look after you."],
    MELB: ["The oldest club in the game wants the freshest mind in it.", "Our 2021 group has one more run in it. You'd find it."],
    NMFC: ["Arden Street has been waiting for someone like you.", "Shinboners don't give up. Neither do you. Call me."],
    PORT: ["Alberton wants a flag, not a fairytale. Ring me.", "We exist to win. Right now we're not. Fix it."],
    RICH: ["We've done this before. We need a coach who can do it again.", "Punt Road is quiet. Come make it loud again."],
    STK: ["One flag in our history. Write the next chapter.", "Moorabbin still dreams. Give the Saints something real."],
    SYD: ["The board's already approved it. Just say yes.", "Red and white, Bloods culture, harbour views. Easy call."],
    WCE: ["Our young core watched your grand final twice. They want you.", "Perth is the loudest home crowd in the game. Come hear it."],
    WB: ["The Kennel has been hungry since 2016. So are you.", "Sons of the West want another flag. Call me back."],
  }),
];
