import { anyLines, byStatus, clubLines, p, type Phrase } from "./types";

/** Offers screen side-panel quote. Speaker: the club president, selling the job in one or two sentences. */
export const offerPitch: Phrase[] = [
  ...anyLines("offerPitch", [
    "We've read every one of your game-plan notes. We want the rest in person.",
    "Your side won the contested ball and the space. We'd like both.",
    "Name the staff you want. We'll find the budget.",
  ]),
  ...byStatus("offerPitch", "contender", [
    "We've built the list. We need the coach who can finish it off.",
    "Close is no longer good enough. You get us over the line.",
    "Top-four list, top-four money, and a coach's box with your name on it.",
    "{star} is in his prime. Don't waste a year of it anywhere else.",
    "Two years, one job: bring the cup home.",
    "Every stat we track says we're a contender. You'd make it a certainty.",
    "Our ball movement is a step behind. Yours is two steps ahead.",
    "You don't take this job to build. You take it to win.",
  ], "hungry"),
  ...byStatus("offerPitch", "rising", [
    "The kids are ready. We need someone to tell them they're ready.",
    "{topYoungster} and this young group will run through walls for a coach like you.",
    "Finished {finish}, getting better every month. Imagine us with your system.",
    "Youngest engine in the league, and nobody's taught it to turn yet.",
    "Come early and the premiership window will open on your watch.",
    "Your transition game suits our legs perfectly.",
    "It's the most exciting list in the competition. Coach it.",
    "We're a club on the way up. Get on board before everyone notices.",
  ], "warm"),
  ...byStatus("offerPitch", "middle", [
    "We've got the talent. You've got the plan.",
    "Good enough to make finals, not good enough to win one. That's your gap to close.",
    "We finished {finish}. The list says we should be higher, and so do your numbers.",
    "A solid list with no identity. Give it yours.",
    "Nobody is scared of us. Make them scared.",
    "Three years to turn a middle side into a September side.",
    "Your pressure model and our midfield would be a real problem for the league.",
    "Honest list, honest club, and a board that will back you.",
  ], "measured"),
  ...byStatus("offerPitch", "sleepingGiant", [
    "This club hasn't been this hungry in twenty years. Neither have you.",
    "Biggest crowds, biggest expectations, biggest reward if you get it right.",
    "Wake us up and they'll build you a statue.",
    "For a club this size, {finish} is a crisis. You're the answer.",
    "The members have waited long enough. Give them September.",
    "A giant club that forgot how to win. Remind it.",
    "Money is not the problem here. Direction is.",
    "Every young coach wants a big club. This is the biggest job going.",
  ], "desperate"),
  ...byStatus("offerPitch", "reset", [
    "We've lost our way. You're the map.",
    "The list is better than {finish}. We need the coach who proves it.",
    "It's a reset, not a teardown. One pre-season with you and we're back.",
    "Talent on the list, confusion on the field. Clear it up.",
    "Four years, full support, and a group that wants to be coached.",
    "We don't need new players. We need new ideas.",
    "Our stoppage numbers fell off a cliff. Yours are the best in the country.",
    "Give this group a system and it'll give you results.",
  ], "blunt"),
  ...byStatus("offerPitch", "rebuild", [
    "{years} years, full backing, no noise. Just make {topYoungster} and the kids great.",
    "Five years, full backing, no noise. Just make them great.",
    "Draft picks, cap space and patience. The only thing missing is you.",
    "Nobody expects anything after {finish}, which is exactly why you'd love it.",
    "Build the culture first. The wins come later, and we'll wait for them.",
    "A blank page and a long contract. Write us a dynasty.",
    "Our young players need a teacher. Everyone says that's what you are.",
    "You get to pick the list, the staff and the style. Total control.",
  ], "warm"),
  ...[
    p("offerPitch.interstate.01", "Bring the family over. Schools, house, the lot, all sorted before you land.", { isInterstate: true }),
    p("offerPitch.interstate.02", "A one-team town that lives and breathes the {nick}. You'd never want to leave.", { isInterstate: true }),
    p("offerPitch.interstate.03", "Get away from the Melbourne noise. Out here you can just coach.", { isInterstate: true }),
    p("offerPitch.interstate.04", "Moving states is a big call. We'll make it the easiest one you ever make.", { isInterstate: true }),
    p("offerPitch.interstate.05", "The {state} footy public will adopt you by Round 3. Promise.", { isInterstate: true }),
    p("offerPitch.oldstar.01", "{star} has maybe two years left at his best. Help him win one.", { starAgeMin: 30 }),
    p("offerPitch.oldstar.02", "Our champion {starPos} is on the back nine. Give him a finish worth having.", { starAgeMin: 30 }),
    p("offerPitch.oldstar.03", "Win now for {star}, build later for the rest. You can do both.", { starAgeMin: 30 }),
    p("offerPitch.oldstar.04", "{star} said he'd go around again if we landed you.", { starAgeMin: 30 }),
    p("offerPitch.kidstar.01", "{star} is the best young player in the game. Build it all around him.", { starAgeMax: 22 }),
    p("offerPitch.kidstar.02", "A generational kid at the top of our list. Don't let someone else coach him.", { starAgeMax: 22 }),
    p("offerPitch.kidstar.03", "{star} is barely out of school and already our best. Shape the next decade.", { starAgeMax: 22 }),
    p("offerPitch.kidstar.04", "Get {star} for the next ten years, and get him first.", { starAgeMax: 22 }),
    p("offerPitch.WCE.kid", "We have the best young player in the game. Now we need the best young coach.", { club: ["WCE"], starAgeMax: 22 }),
  ],
  ...clubLines("offerPitch", {
    ADEL: ["Adelaide Oval on Showdown night is the loudest room in footy. It could be yours.", "Two flags in the late nineties. The Crows want a third, and they want your plan.", "Saturday in Adelaide is all Crows. You'd be the one they talk about."],
    BL: ["The last bloke won us a cup. We think you'll win us three.", "The Gabba loves a winner, and we've got the habit now. Keep it going.", "Fitzroy blood, Brisbane heart. This club knows how to win flags."],
    CARL: ["Sixty thousand members are tired of waiting. So are we.", "Sixteen flags, and not one since 1995. Break the drought.", "Princes Park history and a Marvel future. Be the coach who joins them."],
    COLL: ["The Daicos era deserves a coach who thinks like him.", "It's Collingwood. Everyone will be watching. Good.", "Black and white, the biggest club in the land. Nothing else compares."],
    ESS: ["Windy Hill still has your photo from the VFL grand final on the wall. Come make it official.", "More than twenty years without a final win. You're the one to end it.", "Sixteen flags, a red sash and a membership that won't stop growing. Take the job."],
    FRE: ["Great mids, no flag. We need the mind.", "Freo has never won a flag. Be the coach who does it first.", "Purple, proud and ready. The port city wants a premiership."],
    GEEL: ["We don't rebuild. We reload. Help us reload.", "Kardinia Park is a fortress. You'd make it a dynasty again.", "Four flags since 2007. The Cats want to keep the standard."],
    GCFC: ["Our first final win was just the start. You're the next part.", "Youngest club in the league, oldest ambition in the game.", "Sunshine, a young list and no Melbourne media. Coach in peace."],
    GWS: ["We keep knocking on the door. Kick it in for us.", "A club built for a flag. It just needs the coach to win one.", "Western Sydney is the next frontier. Be the one who takes it."],
    HAW: ["This club knows how to build dynasties. Build us the next one.", "Brown and gold, three-peat pedigree. We know what great looks like.", "The family club wants you in the family. Call it a homecoming."],
    MELB: ["The oldest club in the world wants the newest ideas in it.", "We broke a 57-year drought in 2021. Don't make us start another one.", "Red and blue at the MCG, every week. Fill it again."],
    NMFC: ["Arden Street will wait for you. Long deal, no noise, full backing.", "The Shinboner spirit plus your structures. That's a flag in the making.", "We've been at the bottom long enough. Take us back up."],
    PORT: ["We exist to win. Right now we're not. Fix it.", "Alberton has premiership DNA. It needs a coach to switch it on.", "Never tear us apart. Come and build us back up."],
    RICH: ["We've done this before. We need a coach who can do it again.", "Three flags in four years, then the fall. Start the next climb.", "The Tiger Army will follow you anywhere. Lead them."],
    STK: ["One flag in our history. Write the next chapter.", "Moorabbin grit and a young core. Give the Saints a September.", "When the Saints go marching in, we want you out in front."],
    SYD: ["The Swans way is winning. You'll fit right in.", "Bloods culture, SCG crowds and a board that backs its coach.", "Two flags since the move north. Make it three."],
    WCE: ["Our first flag made history. Help us write a new chapter.", "Optus Stadium, sixty thousand, every home game. Come coach them.", "A proud club at the bottom. The climb back starts with you."],
    WB: ["Talent at the Kennel, and a plan in your notebook. Perfect match.", "2016 ended a 62-year wait. We don't want to wait that long again.", "Sons of the West, a young core and a fearless style. Sounds like you."],
  }),
];
