import type { RatedAttribute } from "../types/player.ts";
import { RATED_ATTRIBUTES } from "../types/player.ts";
import type { Real2026SeasonStats } from "../data/real2026SeasonStats.ts";
import type { Archetype } from "../types/archetype.ts";

/**
 * Round C142 — [[End-of-2026 Player Database Refresh]] Step 2. The real-stat-to-attribute
 * generation formula, written from scratch and committed for the first time (Schema.md's own
 * honesty note, reconfirmed this round: the original formula existed only inside an offline,
 * never-committed script — "documented in full in the generation script" turned out to mean a
 * script that was never checked in anywhere). Nothing here reconstructs lost coefficients; this is
 * a fresh, disclosed implementation of Schema.md's "Rated attributes" input table (the *which
 * stats feed which attribute* mapping, which IS documented) using the same z-score-and-rescale
 * idiom `progression.ts`'s `ovrFromRawComposite` already uses for `OVR` (`50 + z * 13`, clipped).
 *
 * **Population**: z-scores are computed across the 594 players in `data/real2026SeasonStats.ts`
 * (every player with a confirmed real 2026 AFL season row) — see the design note for why the
 * other 157 players have no real 2026 row to generate from at all (not a scrape failure: they
 * didn't play a senior game in the real 2026 season).
 *
 * **Disclosed simplifications, all because Schema.md documents WHICH stats feed an attribute but
 * never the exact coefficients or weighting scheme (there is nothing to reconstruct — this is new
 * code implementing an old spec)**:
 * - Each attribute is the unweighted mean of its documented input z-scores (a documented
 *   "(inverse)" input is negated before averaging).
 * - `acceleration` and `speed` are documented against the literal same three inputs
 *   (bounces/g, inside-50s/g, rebound-50s/g) — reproduced as-is rather than inventing a
 *   distinguishing input the schema doesn't mention, so the two will correlate strongly by
 *   construction. Flagged here rather than silently "fixed" by guessing.
 * - `positioning`'s documented "sign flips defender vs forward" is implemented as a change of
 *   INPUT (defenders read off rebound-50s/one-percenters; forwards off inside-50s) rather than a
 *   literal sign flip on one shared number — the two real-world signals aren't the same stat with
 *   an opposite sign, so this achieves the intended effect without pretending they are.
 * - `consistancy`'s second documented input ("% of game played") has no real-stat source in
 *   `real2026SeasonStats.ts` (no minutes/time-on-ground column exists in the source spreadsheet) —
 *   `consistancy` is generated from real games played alone. Disclosed limitation, not silently
 *   dropped.
 * - `kickMaxDistance`'s documented "archetype size" component is a small fixed z-bonus for the
 *   four tallest archetypes (Ruck, Hybrid Key Forward Ruck, Key Forward, Key Defender) — a
 *   plausible, disclosed stand-in for a real height-based coefficient this project has no
 *   grounded source to derive.
 *
 * **Not regenerated by this file** (left untouched by the round C142 refresh script even for the
 * 594 matched players): `diciplineMatch`, `umpireLikes`/`umpireNotice`, `goHomeTend`, `injuryTend`,
 * `leadership` — all documented MODELLED-from-stats fields, but out of this round's scope (the
 * design note's Step 2 ask was specifically "the real-stat-to-attribute generation script," i.e.
 * the 20 `RATED_ATTRIBUTES`). `clangerTend` IS regenerated here since Schema.md tags it REAL
 * ("directly derived from real clangers/game") and leaving it stale while `stat_CL` itself updates
 * would be a real inconsistency, not just an out-of-scope field.
 */

const DEFENDER_ARCHETYPES: readonly Archetype[] = ["Medium Defender", "Intercept Defender", "Half Back Flanker", "Back Pocket", "Key Defender"];
const FORWARD_ARCHETYPES: readonly Archetype[] = ["Pressure Forward", "Hybrid Mid Forward", "Small Forward", "Medium Forward", "Key Forward", "Hybrid Key Forward Ruck"];
const TALL_ARCHETYPES: readonly Archetype[] = ["Ruck", "Hybrid Key Forward Ruck", "Key Forward", "Key Defender"];

interface PerGameRates {
  realFullName: string;
  games: number;
  kicksPg: number;
  marksPg: number;
  handballsPg: number;
  disposalsPg: number;
  goalsPg: number;
  hitoutsPg: number;
  tacklesPg: number;
  rebound50sPg: number;
  inside50sPg: number;
  clearancesPg: number;
  clangersPg: number;
  freesForPg: number;
  freesAgainstPg: number;
  brownlowVotesPg: number;
  contestedPossPg: number;
  uncontestedPossPg: number;
  contestedMarksPg: number;
  marksInside50Pg: number;
  onePercentersPg: number;
  bouncesPg: number;
  goalAssistsPg: number;
  totalPossPg: number;
}

function perGame(s: Real2026SeasonStats): PerGameRates {
  const g = s.games > 0 ? s.games : 1; // guard: a real-but-0-games 2026 row reads as all-zero rates, not divide-by-zero
  return {
    realFullName: s.realFullName,
    games: s.games,
    kicksPg: s.kicks / g,
    marksPg: s.marks / g,
    handballsPg: s.handballs / g,
    disposalsPg: s.disposals / g,
    goalsPg: s.goals / g,
    hitoutsPg: s.hitouts / g,
    tacklesPg: s.tackles / g,
    rebound50sPg: s.rebound50s / g,
    inside50sPg: s.inside50s / g,
    clearancesPg: s.clearances / g,
    clangersPg: s.clangers / g,
    freesForPg: s.freesFor / g,
    freesAgainstPg: s.freesAgainst / g,
    brownlowVotesPg: s.brownlowVotes / g,
    contestedPossPg: s.contestedPoss / g,
    uncontestedPossPg: s.uncontestedPoss / g,
    contestedMarksPg: s.contestedMarks / g,
    marksInside50Pg: s.marksInside50 / g,
    onePercentersPg: s.onePercenters / g,
    bouncesPg: s.bounces / g,
    goalAssistsPg: s.goalAssists / g,
    totalPossPg: (s.contestedPoss + s.uncontestedPoss) / g,
  };
}

interface FieldStats {
  mean: number;
  stdDev: number;
}

function fieldStats(values: readonly number[]): FieldStats {
  const n = values.length;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  const variance = values.reduce((a, b) => a + (b - mean) ** 2, 0) / n;
  return { mean, stdDev: Math.sqrt(variance) };
}

type RateKey = keyof Omit<PerGameRates, "realFullName">;

/** Precomputed population mean/stdDev for every per-game rate this file z-scores against. Built once per `generateAttributesFor2026` call across the passed-in population (never hardcoded — stays correct if the 594-player pool changes). */
export class AttributeZScorer {
  private readonly rows: Map<string, PerGameRates>;
  private readonly stats: Map<RateKey, FieldStats>;

  constructor(seasonStats: readonly Real2026SeasonStats[]) {
    const rates = seasonStats.map(perGame);
    this.rows = new Map(rates.map((r) => [r.realFullName, r]));
    const keys: RateKey[] = [
      "games", "kicksPg", "marksPg", "handballsPg", "disposalsPg", "goalsPg", "hitoutsPg", "tacklesPg",
      "rebound50sPg", "inside50sPg", "clearancesPg", "clangersPg", "freesForPg", "freesAgainstPg",
      "brownlowVotesPg", "contestedPossPg", "uncontestedPossPg", "contestedMarksPg", "marksInside50Pg",
      "onePercentersPg", "bouncesPg", "goalAssistsPg", "totalPossPg",
    ];
    this.stats = new Map(keys.map((k) => [k, fieldStats(rates.map((r) => r[k]))]));
  }

  private z(realFullName: string, key: RateKey): number {
    const row = this.rows.get(realFullName);
    if (!row) return 0;
    const s = this.stats.get(key)!;
    if (s.stdDev === 0) return 0;
    return (row[key] - s.mean) / s.stdDev;
  }

  private rescale(zCombined: number, bonus = 0): number {
    return Math.max(1, Math.min(99, Math.round(50 + (zCombined + bonus) * 13)));
  }

  /** The 20 `RATED_ATTRIBUTES` for one real player, per Schema.md's documented input table (see this file's own header comment for the disclosed simplifications). `realFullName` must have a row in the `Real2026SeasonStats` population this scorer was built from. */
  attributesFor(realFullName: string, archetype: Archetype): Record<RatedAttribute, number> {
    const z = (k: RateKey) => this.z(realFullName, k);
    const avg = (...vs: number[]) => vs.reduce((a, b) => a + b, 0) / vs.length;

    const isDefender = DEFENDER_ARCHETYPES.includes(archetype);
    const isForward = FORWARD_ARCHETYPES.includes(archetype);
    const positioningZ = isDefender
      ? avg(z("rebound50sPg"), z("onePercentersPg"))
      : isForward
        ? z("inside50sPg")
        : avg(z("inside50sPg"), z("rebound50sPg")) * 0.5;
    const tallBonus = TALL_ARCHETYPES.includes(archetype) ? 0.3 : 0;

    const out: Record<RatedAttribute, number> = {
      manMarking: this.rescale(avg(z("marksPg"), z("contestedMarksPg"))),
      verticalLeap: this.rescale(avg(z("contestedMarksPg"), z("marksInside50Pg"), z("hitoutsPg"))),
      tenacity: this.rescale(avg(z("tacklesPg"), z("contestedPossPg"))),
      skill: this.rescale(avg(z("disposalsPg"), z("kicksPg"), -z("clangersPg"))),
      agility: this.rescale(avg(z("uncontestedPossPg"), z("bouncesPg"), z("inside50sPg"))),
      courage: this.rescale(avg(z("contestedPossPg"), z("tacklesPg"), z("freesAgainstPg"))),
      aggression: this.rescale(avg(z("tacklesPg"), z("freesAgainstPg"), z("clangersPg"))),
      xFactor: this.rescale(avg(z("brownlowVotesPg"), z("goalAssistsPg"), z("contestedMarksPg"))),
      strengthGroundLevel: this.rescale(avg(z("contestedPossPg"), z("handballsPg"))),
      strengthOverhead: this.rescale(avg(z("contestedMarksPg"), z("marksPg"))),
      strengthManOnMan: this.rescale(avg(z("onePercentersPg"), z("tacklesPg"))),
      acceleration: this.rescale(avg(z("bouncesPg"), z("inside50sPg"), z("rebound50sPg"))),
      speed: this.rescale(avg(z("bouncesPg"), z("rebound50sPg"), z("inside50sPg"))),
      endurance: this.rescale(avg(z("games"), z("disposalsPg"))),
      confidence: this.rescale(avg(z("goalsPg"), z("brownlowVotesPg"), z("disposalsPg"))),
      readPlay: this.rescale(avg(z("totalPossPg"), z("inside50sPg"))),
      consistancy: this.rescale(z("games")),
      positioning: this.rescale(positioningZ),
      copeWithPressure: this.rescale(avg(z("contestedPossPg"), z("tacklesPg"), -z("clangersPg"))),
      kickMaxDistance: this.rescale(avg(z("kicksPg"), z("inside50sPg")), tallBonus),
    };
    for (const a of RATED_ATTRIBUTES) {
      if (!(a in out)) throw new Error(`attributeGeneration: missing rated attribute ${a}`);
    }
    return out;
  }

  /** `clangerTend` — Schema.md tags this REAL ("directly derived from real clangers/game"), not one of the 20 `RATED_ATTRIBUTES`, but regenerated alongside them for the same 594 players since it shares the same real-stat input that's being refreshed. */
  clangerTendFor(realFullName: string): number {
    return this.rescale(this.z(realFullName, "clangersPg"));
  }
}
