import type { RatedAttribute } from "../types/player.ts";
import { RATED_ATTRIBUTES } from "../types/player.ts";
import type { Real2026SeasonStats } from "../data/real2026SeasonStats.ts";
import type { Archetype } from "../types/archetype.ts";

/**
 * Round C142 — [[End-of-2026 Player Database Refresh]] Step 2. The real-stat-to-attribute
 * generation formula, written from scratch and committed for the first time (Schema.md's own
 * honesty note, reconfirmed this round: the original formula existed only inside an offline,
 * never-committed script — "documented in full in the generation script" turned out to mean a
 * script that was never checked in anywhere). Nothing here reconstructs lost coefficients; this is
 * a fresh, disclosed implementation of Schema.md's "Rated attributes" input table (the *which
 * stats feed which attribute* mapping, which IS documented) using the same z-score-and-rescale
 * idiom `progression.ts`'s `ovrFromRawComposite` already uses for `OVR` (`50 + z * 13`, clipped).
 *
 * **Population**: z-scores are computed across the 594 players in `data/real2026SeasonStats.ts`
 * (every player with a confirmed real 2026 AFL season row) — see the design note for why the
 * other 157 players have no real 2026 row to generate from at all (not a scrape failure: they
 * didn't play a senior game in the real 2026 season).
 *
 * **Disclosed simplifications, all because Schema.md documents WHICH stats feed an attribute but
 * never the exact coefficients or weighting scheme (there is nothing to reconstruct — this is new
 * code implementing an old spec)**:
 * - Each attribute is the unweighted mean of its documented input z-scores (a documented
 *   "(inverse)" input is negated before averaging).
 * - `acceleration` and `speed` are documented against the literal same three inputs
 *   (bounces/g, inside-50s/g, rebound-50s/g) — reproduced as-is rather than inventing a
 *   distinguishing input the schema doesn't mention, so the two will correlate strongly by
 *   construction. Flagged here rather than silently "fixed" by guessing.
 * - `positioning`'s documented "sign flips defender vs forward" is implemented as a change of
 *   INPUT (defenders read off rebound-50s/one-percenters; forwards off inside-50s) rather than a
 *   literal sign flip on one shared number — the two real-world signals aren't the same stat with
 *   an opposite sign, so this achieves the intended effect without pretending they are.
 * - `consistancy`'s second documented input ("% of game played") has no real-stat source in
 *   `real2026SeasonStats.ts` (no minutes/time-on-ground column exists in the source spreadsheet) —
 *   `consistancy` is generated from real games played alone. Disclosed limitation, not silently
 *   dropped.
 * - `kickMaxDistance`'s documented "archetype size" component is a small fixed z-bonus for the
 *   four tallest archetypes (Ruck, Hybrid Key Forward Ruck, Key Forward, Key Defender) — a
 *   plausible, disclosed stand-in for a real height-based coefficient this project has no
 *   grounded source to derive.
 *
 * **Not regenerated by this file** (left untouched by the round C142 refresh script even for the
 * 594 matched players): `diciplineMatch`, `umpireLikes`/`umpireNotice`, `goHomeTend`, `injuryTend`,
 * `leadership` — all documented MODELLED-from-stats fields, but out of this round's scope (the
 * design note's Step 2 ask was specifically "the real-stat-to-attribute generation script," i.e.
 * the 20 `RATED_ATTRIBUTES`). `clangerTend` IS regenerated here since Schema.md tags it REAL
 * ("directly derived from real clangers/game") and leaving it stale while `stat_CL` itself updates
 * would be a real inconsistency, not just an out-of-scope field.
 */

const DEFENDER_ARCHETYPES: readonly Archetype[] = ["Medium Defender", "Intercept Defender", "Half Back Flanker", "Back Pocket", "Key Defender"];
const FORWARD_ARCHETYPES: readonly Archetype[] = ["Pressure Forward", "Hybrid Mid Forward", "Small Forward", "Medium Forward", "Key Forward", "Hybrid Key Forward Ruck"];
const TALL_ARCHETYPES: readonly Archetype[] = ["Ruck", "Hybrid Key Forward Ruck", "Key Forward", "Key Defender"];

interface PerGameRates {
  realFullName: string;
  games: number;
  kicksPg: number;
  marksPg: number;
  handballsPg: number;
  disposalsPg: number;
  goalsPg: number;
  hitoutsPg: number;
  tacklesPg: number;
  rebound50sPg: number;
  inside50sPg: number;
  clearancesPg: number;
  clangersPg: number;
  freesForPg: number;
  freesAgainstPg: number;
  brownlowVotesPg: number;
  contestedPossPg: number;
  uncontestedPossPg: number;
  contestedMarksPg: number;
  marksInside50Pg: number;
  onePercentersPg: number;
  bouncesPg: number;
  goalAssistsPg: number;
  totalPossPg: number;
}

function perGame(s: Real2026SeasonStats): PerGameRates {
  const g = s.games > 0 ? s.games : 1; // guard: a real-but-0-games 2026 row reads as all-zero rates, not divide-by-zero
  return {
    realFullName: s.realFullName,
    games: s.games,
    kicksPg: s.kicks / g,
    marksPg: s.marks / g,
    handballsPg: s.handballs / g,
    disposalsPg: s.disposals / g,
    goalsPg: s.goals / g,
    hitoutsPg: s.hitouts / g,
    tacklesPg: s.tackles / g,
    rebound50sPg: s.rebound50s / g,
    inside50sPg: s.inside50s / g,
    clearancesPg: s.clearances / g,
    clangersPg: s.clangers / g,
    freesForPg: s.freesFor / g,
    freesAgainstPg: s.freesAgainst / g,
    brownlowVotesPg: s.brownlowVotes / g,
    contestedPossPg: s.contestedPoss / g,
    uncontestedPossPg: s.uncontestedPoss / g,
    contestedMarksPg: s.contestedMarks / g,
    marksInside50Pg: s.marksInside50 / g,
    onePercentersPg: s.onePercenters / g,
    bouncesPg: s.bounces / g,
    goalAssistsPg: s.goalAssists / g,
    totalPossPg: (s.contestedPoss + s.uncontestedPoss) / g,
  };
}

interface FieldStats {
  mean: number;
  stdDev: number;
}

function fieldStats(values: readonly number[]): FieldStats {
  const n = values.length;
  const mean = values.reduce((a, b) => a + b, 0) / n;
  const variance = values.reduce((a, b) => a + (b - mean) ** 2, 0) / n;
  return { mean, stdDev: Math.sqrt(variance) };
}

type RateKey = keyof Omit<PerGameRates, "realFullName">;

/** Precomputed population mean/stdDev for every per-game rate this file z-scores against. Built once per `generateAttributesFor2026` call across the passed-in population (never hardcoded — stays correct if the 594-player pool changes). */
export class AttributeZScorer {
  private readonly rows: Map<string, PerGameRates>;
  private readonly stats: Map<RateKey, FieldStats>;

  constructor(seasonStats: readonly Real2026SeasonStats[]) {
    const rates = seasonStats.map(perGame);
    this.rows = new Map(rates.map((r) => [r.realFullName, r]));
    const keys: RateKey[] = [
      "games", "kicksPg", "marksPg", "handballsPg", "disposalsPg", "goalsPg", "hitoutsPg", "tacklesPg",
      "rebound50sPg", "inside50sPg", "clearancesPg", "clangersPg", "freesForPg", "freesAgainstPg",
      "brownlowVotesPg", "contestedPossPg", "uncontestedPossPg", "contestedMarksPg", "marksInside50Pg",
      "onePercentersPg", "bouncesPg", "goalAssistsPg", "totalPossPg",
    ];
    this.stats = new Map(keys.map((k) => [k, fieldStats(rates.map((r) => r[k]))]));
  }

  private z(realFullName: string, key: RateKey): number {
    const row = this.rows.get(realFullName);
    if (!row) return 0;
    return this.zOfRow(row, key);
  }

  /**
   * Round C148 — z-score an arbitrary `PerGameRates` row against this scorer's already-built
   * population field stats, without requiring that row to be one of the ones the scorer was
   * constructed from. Powers `attributesForExternalRow` below, which `recencyForm.ts`'s recency-
   * blended synthetic rows and `historicalOvrReconstruction.ts`'s past-season rows both need: a
   * historical or recency-blended stat line isn't itself a member of the CURRENT population this
   * scorer's field means/stdDevs were computed from, but it should still be measured against that
   * same fixed reference (see this round's design note for why a fixed current-population baseline
   * is the disclosed, reasonable choice — there's no real same-year historical league population in
   * this dataset to z-score against instead).
   */
  private zOfRow(row: PerGameRates, key: RateKey): number {
    const s = this.stats.get(key)!;
    if (s.stdDev === 0) return 0;
    return (row[key] - s.mean) / s.stdDev;
  }

  /**
   * Round C147 rescale — [[End-of-2026 Player Database Refresh]] Step 3: `70 + z*13`, clipped
   * `[40, 110]`, replacing the old `50 + z*13` clipped `[1, 99]` — the same recentre-and-extend
   * `progression.ts`'s `ovrFromRawComposite` now uses for `OVR`, applied here to all 20
   * `RATED_ATTRIBUTES` too per Tyler's own round-125 "rescale everything" decision. `clangerTend`
   * (`clangerTendFor` below) deliberately stays on the OLD `[1, 99]` scale — it's tagged REAL in
   * Schema.md, not one of the 20 `RATED_ATTRIBUTES` this round's rescale scope covers, and nothing
   * in the match engine reads it on the new attribute scale.
   */
  private rescale(zCombined: number, bonus = 0): number {
    return Math.max(40, Math.min(110, Math.round(70 + (zCombined + bonus) * 13)));
  }

  /** `clangerTendFor` reuses the OLD `[1, 99]` scale deliberately — see this file's `rescale` doc comment. */
  private rescaleOldScale(zCombined: number): number {
    return Math.max(1, Math.min(99, Math.round(50 + zCombined * 13)));
  }

  /** The 20 `RATED_ATTRIBUTES` for one real player, per Schema.md's documented input table (see this file's own header comment for the disclosed simplifications). `realFullName` must have a row in the `Real2026SeasonStats` population this scorer was built from. */
  attributesFor(realFullName: string, archetype: Archetype): Record<RatedAttribute, number> {
    return this.computeAttributes((k) => this.z(realFullName, k), archetype);
  }

  /**
   * Round C148 — the same 20-attribute formula as `attributesFor`, but for an arbitrary
   * `Real2026SeasonStats`-shaped row that ISN'T necessarily a member of the population this scorer
   * was constructed from (a recency-blended synthetic row from `recencyForm.ts`, or a past real
   * season's row from `historicalOvrReconstruction.ts`) — z-scored against this scorer's fixed
   * population field stats regardless (see `zOfRow`'s own doc comment for why that's the disclosed,
   * reasonable choice here).
   */
  attributesForExternalRow(row: Real2026SeasonStats, archetype: Archetype): Record<RatedAttribute, number> {
    const rates = perGame(row);
    return this.computeAttributes((k) => this.zOfRow(rates, k), archetype);
  }

  private computeAttributes(z: (k: RateKey) => number, archetype: Archetype): Record<RatedAttribute, number> {
    const avg = (...vs: number[]) => vs.reduce((a, b) => a + b, 0) / vs.length;
    // Round C149 — [[End-of-2026 Player Database Refresh]]: a weighted-average helper, alongside
    // the existing unweighted `avg`, so a specific input can be given more than 1/n share of an
    // attribute's z-score without inventing a whole second averaging convention. Used below only
    // where this round's diagnosis found a genuinely mismatched equal-weighting (see this file's
    // own new doc paragraph on the archetype-weighting bias fix for the full reasoning) — every
    // other attribute keeps its existing unweighted `avg` untouched.
    const wavg = (pairs: readonly [number, number][]) => {
      let sum = 0, weight = 0;
      for (const [v, w] of pairs) { sum += v * w; weight += w; }
      return sum / weight;
    };

    const isDefender = DEFENDER_ARCHETYPES.includes(archetype);
    const isForward = FORWARD_ARCHETYPES.includes(archetype);
    const positioningZ = isDefender
      ? avg(z("rebound50sPg"), z("onePercentersPg"))
      : isForward
        ? z("inside50sPg")
        : avg(z("inside50sPg"), z("rebound50sPg")) * 0.5;
    const tallBonus = TALL_ARCHETYPES.includes(archetype) ? 0.3 : 0;

    const out: Record<RatedAttribute, number> = {
      manMarking: this.rescale(avg(z("marksPg"), z("contestedMarksPg"))),
      // Round C149: hitoutsPg now weighted 2x within verticalLeap (was an equal 1/3 share with
      // contestedMarksPg/marksInside50Pg) — see this file's own new doc paragraph below for why:
      // hitouts is THE real-stat signal a Ruck/Key-Forward-relief-ruck actually dominates, and
      // diluting it to an equal third alongside two marking stats rucks are mediocre at (they're
      // not the competition's best overhead markers, they're the competition's best tap players)
      // was actively suppressing the one archetype this attribute is supposed to anchor for.
      verticalLeap: this.rescale(wavg([[z("contestedMarksPg"), 1], [z("marksInside50Pg"), 1], [z("hitoutsPg"), 2]])),
      tenacity: this.rescale(avg(z("tacklesPg"), z("contestedPossPg"))),
      skill: this.rescale(avg(z("disposalsPg"), z("kicksPg"), -z("clangersPg"))),
      agility: this.rescale(avg(z("uncontestedPossPg"), z("bouncesPg"), z("inside50sPg"))),
      courage: this.rescale(avg(z("contestedPossPg"), z("tacklesPg"), z("freesAgainstPg"))),
      aggression: this.rescale(avg(z("tacklesPg"), z("freesAgainstPg"), z("clangersPg"))),
      // Round C149: contestedMarksPg -> tacklesPg. xFactor is a primary (x3) attribute for Small
      // Forward and Hybrid Mid Forward, and contestedMarksPg structurally punishes small,
      // ground-level players for not being tall overhead markers — the opposite of what
      // "x-factor" is supposed to reward for that archetype. tacklesPg (relentless tackling
      // pressure/turnover creation) is the real small-forward "x-factor" signal media/scouting
      // actually describes (see this file's own `ARCHETYPE_TACTICAL_PHRASES` Small Forward entry:
      // "snapping opportunistically and locking it inside forward 50 with relentless tackling").
      xFactor: this.rescale(avg(z("brownlowVotesPg"), z("goalAssistsPg"), z("tacklesPg"))),
      strengthGroundLevel: this.rescale(avg(z("contestedPossPg"), z("handballsPg"))),
      strengthOverhead: this.rescale(avg(z("contestedMarksPg"), z("marksPg"))),
      strengthManOnMan: this.rescale(avg(z("onePercentersPg"), z("tacklesPg"))),
      acceleration: this.rescale(avg(z("bouncesPg"), z("inside50sPg"), z("rebound50sPg"))),
      speed: this.rescale(avg(z("bouncesPg"), z("rebound50sPg"), z("inside50sPg"))),
      // Round C149: disposalsPg -> hitoutsPg added alongside it (not replacing it — endurance's
      // "workrate" half should recognise ANY high-value repeated real work, not only touch
      // volume). Old formula structurally read Rucks as low-endurance purely because rucks
      // register fewer disposals per game than midfielders, despite rucks routinely playing the
      // most total minutes/highest work-rate role on the ground — the exact "goal/hitout volume
      // under-rewarded relative to disposal volume" gap this round's brief named directly.
      endurance: this.rescale(avg(z("games"), z("disposalsPg"), z("hitoutsPg"))),
      // Round C149: disposalsPg -> goalAssistsPg. confidence is a primary (x3) attribute for Key
      // Forward, Hybrid Mid Forward, Small Forward and Medium Forward — every one of them a
      // goal-scoring-focused archetype whose real disposal COUNT is structurally low next to a
      // midfielder's, despite genuine scoreboard-impact quality. goalAssistsPg keeps confidence's
      // documented "goals/g, Brownlow votes/g" scoring-impact spine intact while swapping its
      // third input for another real scoring-adjacent signal instead of raw touch volume.
      confidence: this.rescale(avg(z("goalsPg"), z("brownlowVotesPg"), z("goalAssistsPg"))),
      readPlay: this.rescale(avg(z("totalPossPg"), z("inside50sPg"))),
      consistancy: this.rescale(z("games")),
      positioning: this.rescale(positioningZ),
      copeWithPressure: this.rescale(avg(z("contestedPossPg"), z("tacklesPg"), -z("clangersPg"))),
      kickMaxDistance: this.rescale(avg(z("kicksPg"), z("inside50sPg")), tallBonus),
    };
    for (const a of RATED_ATTRIBUTES) {
      if (!(a in out)) throw new Error(`attributeGeneration: missing rated attribute ${a}`);
    }
    return out;
  }

  /** `clangerTend` — Schema.md tags this REAL ("directly derived from real clangers/game"), not one of the 20 `RATED_ATTRIBUTES`, but regenerated alongside them for the same 594 players since it shares the same real-stat input that's being refreshed. */
  clangerTendFor(realFullName: string): number {
    return this.rescaleOldScale(this.z(realFullName, "clangersPg"));
  }
}
