// The `with { type: "json" }` import attribute is the modern standard syntax
// (Vite 5+ and Node 22+ both support it) — included so this file works
// identically whether it's bundled by Vite or run directly under plain Node
// (e.g. scripts/simulate.ts importing this from a headless balance run).
import playersJson from "./generated/players.json" with { type: "json" };
import type { Player } from "../types/player.ts";

// Generated by `npm run build:data` from ../../../Player Database/players_master.csv
// — see scripts/buildData.ts. Run that script again any time the vault's CSV changes.
// Kept as an untouched, immutable snapshot — the "New Game" baseline every
// save starts from and can be reset back to (see resetPoolToGenerated below).
const GENERATED_PLAYERS: readonly Player[] = playersJson as unknown as Player[];

/**
 * The live, mutable player pool every screen and engine call reads from —
 * see ROADMAP.md's persistence-layer writeup (closes gap #24/#29: "nothing
 * in this app today has a persistent, mutable player-pool concept").
 *
 * Deliberately the *same array object* for the app's entire lifetime,
 * mutated in place (`loadPool` clears and re-pushes; never reassigned) —
 * every existing `import { ALL_PLAYERS } from "./loadPlayers"` across the
 * codebase keeps working unchanged, and every `getPlayersByClub`/
 * `getPlayerById` call always reads whatever's currently live, with zero
 * call-site changes needed anywhere the pool is only ever *read*. Only the
 * handful of call sites that need to react to a pool *change* (off-season
 * aging, and eventually trades/contracts/draft) need anything extra — see
 * `src/store/useSaveStore.ts`'s `poolVersion` counter.
 *
 * Framework-free on purpose, matching Engine.md's "Simulation core: zero
 * DOM/browser dependencies" rule — this file (and everything downstream of
 * it: season.ts, listNeeds.ts, lines.ts, scripts/simulate.ts) must keep
 * working identically under plain Node. The actual browser-only concerns —
 * IndexedDB, React reactivity — live one layer up, in useSaveStore.ts.
 */
export const ALL_PLAYERS: Player[] = [...GENERATED_PLAYERS];

/** Replaces the live pool's contents in place — e.g. hydrating from a loaded save. Does not touch which array object `ALL_PLAYERS` refers to (see its own doc comment). */
export function loadPool(players: readonly Player[]): void {
  ALL_PLAYERS.length = 0;
  ALL_PLAYERS.push(...players);
}

/** Restores the live pool to the freshly-generated baseline — "New Game"/"discard save". */
export function resetPoolToGenerated(): void {
  loadPool(GENERATED_PLAYERS);
}

export function getPlayersByClub(team: string): Player[] {
  return ALL_PLAYERS.filter((p) => p.Team === team);
}

export function getPlayerById(id: number): Player | undefined {
  return ALL_PLAYERS.find((p) => p.PlayerID === id);
}

export function averageOvr(players: readonly Player[]): number {
  if (players.length === 0) return 0;
  return players.reduce((sum, p) => sum + p.OVR, 0) / players.length;
}

/**
 * League-wide average OVR, recomputed fresh from the live pool on every
 * call — deliberately a function, not a cached constant. Used to be a
 * `LEAGUE_AVERAGE_OVR` constant computed once at module load; that went
 * stale the moment the pool could change (a real off-season run recomputes
 * every player's OVR — see engine/progression.ts's `runOffSeason`), so it's
 * removed rather than left as a trap. Matches the reasoning listNeeds.ts's
 * own doc comment already gave for avoiding exactly this const.
 */
export function leagueAverageOvr(): number {
  return averageOvr(ALL_PLAYERS);
}
