import playersJson from "./generated/players.json";
import type { Player } from "../types/player";

// Generated by `npm run build:data` from ../../../Player Database/players_master.csv
// — see scripts/buildData.ts. Run that script again any time the vault's CSV changes.
export const ALL_PLAYERS: Player[] = playersJson as unknown as Player[];

export function getPlayersByClub(team: string): Player[] {
  return ALL_PLAYERS.filter((p) => p.Team === team);
}

export function getPlayerById(id: number): Player | undefined {
  return ALL_PLAYERS.find((p) => p.PlayerID === id);
}

export function averageOvr(players: Player[]): number {
  if (players.length === 0) return 0;
  return players.reduce((sum, p) => sum + p.OVR, 0) / players.length;
}

export const LEAGUE_AVERAGE_OVR = averageOvr(ALL_PLAYERS);
