// The `with { type: "json" }` import attribute is the modern standard syntax
// (Vite 5+ and Node 22+ both support it) — included so this file works
// identically whether it's bundled by Vite or run directly under plain Node
// (e.g. scripts/simulate.ts importing this from a headless balance run).
import playersJson from "./generated/players.json" with { type: "json" };
import type { Player } from "../types/player.ts";
import { playerFullName } from "../types/player.ts";

// Generated by `npm run build:data` from ../../../Player Database/players_master.csv
// — see scripts/buildData.ts. Run that script again any time the vault's CSV changes.
// Kept as an untouched, immutable snapshot — the "New Game" baseline every
// save starts from and can be reset back to (see resetPoolToGenerated below).
const GENERATED_PLAYERS: readonly Player[] = playersJson as unknown as Player[];

/**
 * The live, mutable player pool every screen and engine call reads from —
 * see ROADMAP.md's persistence-layer writeup (closes gap #24/#29: "nothing
 * in this app today has a persistent, mutable player-pool concept").
 *
 * Deliberately the *same array object* for the app's entire lifetime,
 * mutated in place (`loadPool` clears and re-pushes; never reassigned) —
 * every existing `import { ALL_PLAYERS } from "./loadPlayers"` across the
 * codebase keeps working unchanged, and every `getPlayersByClub`/
 * `getPlayerById` call always reads whatever's currently live, with zero
 * call-site changes needed anywhere the pool is only ever *read*. Only the
 * handful of call sites that need to react to a pool *change* (off-season
 * aging, and eventually trades/contracts/draft) need anything extra — see
 * `src/store/useSaveStore.ts`'s `poolVersion` counter.
 *
 * Framework-free on purpose, matching Engine.md's "Simulation core: zero
 * DOM/browser dependencies" rule — this file (and everything downstream of
 * it: season.ts, listNeeds.ts, lines.ts, scripts/simulate.ts) must keep
 * working identically under plain Node. The actual browser-only concerns —
 * IndexedDB, React reactivity — live one layer up, in useSaveStore.ts.
 */
export const ALL_PLAYERS: Player[] = [...GENERATED_PLAYERS];

/** Replaces the live pool's contents in place — e.g. hydrating from a loaded save. Does not touch which array object `ALL_PLAYERS` refers to (see its own doc comment). */
export function loadPool(players: readonly Player[]): void {
  ALL_PLAYERS.length = 0;
  ALL_PLAYERS.push(...players);
}

/** Restores the live pool to the freshly-generated baseline — "New Game"/"discard save". */
export function resetPoolToGenerated(): void {
  loadPool(GENERATED_PLAYERS);
}

/**
 * Excludes `delisted` players (Phase 4 Slice 3, engine/contracts.ts) —
 * every existing caller (Squad List, Selection Committee, List Needs,
 * season simulation, ...) means "who's really on this club's list right
 * now" when it asks this, and a delisted player, by definition, isn't.
 * `ALL_PLAYERS` itself still holds their record (see Player.delisted's own
 * doc comment for why) — this is the one filter point that keeps every
 * downstream screen honest about it without needing its own repeated
 * `!p.delisted` check. Contracts.tsx deliberately reads `ALL_PLAYERS`
 * directly instead of through here, since it's the one screen that
 * legitimately needs to reason about delisted players (if only to exclude
 * them from its own lists too, explicitly).
 */
export function getPlayersByClub(team: string): Player[] {
  return ALL_PLAYERS.filter((p) => p.Team === team && !p.delisted);
}

export function getPlayerById(id: number): Player | undefined {
  return ALL_PLAYERS.find((p) => p.PlayerID === id);
}

/**
 * Reverse of `getPlayerById` — finds a currently-loaded player by their exact "First Last" name.
 * Added for `engine/records.ts`'s real+sim career-continuation merge (Round 60, Tyler: "If I play a
 * game with Scott Pendlebury, will the number of disposals he achieves... be added to the 11,169
 * disposals? If not, it should"): a `RealWorldRecordEntry`'s `name` is checked against the live pool
 * to see whether that real legend is ALSO a currently-loaded, playable AussieFootySim player, so
 * their real career total and their in-save total can be shown as one continuing identity rather
 * than two unrelated rows that happen to share a name.
 *
 * Searches the FULL pool (not `getPlayersByClub`'s delisted-excluded view) — a delisted player's
 * identity still matters here; delisting shouldn't sever the "this is the same person" link. Assumes
 * no two loaded players share an exact full name — verified true of the generated baseline (751
 * players, zero collisions) and reasonable to keep assuming, since this codebase has no player
 * retirement/removal mechanic (see `engine/progression.ts`) — once generated, a player's identity is
 * stable for the life of the save, so this isn't defended against transfer/draft-created collisions
 * beyond that baseline check.
 */
export function getPlayerByFullName(name: string): Player | undefined {
  return ALL_PLAYERS.find((p) => playerFullName(p) === name);
}

/**
 * Round 68 — the real-data-safe sibling of `getPlayerByFullName` above.
 * Matches a player's FROZEN real-world identity (`Player.realFullName`, see
 * that field's own doc comment) instead of their current, possibly-renamed
 * `fname`/`lname`. Every lookup that joins a real-world data file to a
 * currently-loaded player — `draftHistoryFor`/`realSeasonHistoryFor`
 * (`data/realDraftHistory.ts`/`realSeasonHistory.ts`), and
 * `engine/records.ts`'s real+sim career-continuation merge — should call
 * this one, not `getPlayerByFullName`, so a future fictional-name rename
 * can never silently sever that link.
 *
 * Falls back to `playerFullName(p)` for any player missing `realFullName`
 * (a save from before round 68) — before fictionalization ships, the two
 * are identical for every player, so the fallback is always correct today.
 * Same "search the full pool, not delisted-excluded" reasoning as
 * `getPlayerByFullName` — a delisted or renamed player's real-world history
 * still belongs to them.
 */
export function getPlayerByRealFullName(name: string): Player | undefined {
  return ALL_PLAYERS.find((p) => (p.realFullName ?? playerFullName(p)) === name);
}

export function averageOvr(players: readonly Player[]): number {
  if (players.length === 0) return 0;
  return players.reduce((sum, p) => sum + p.OVR, 0) / players.length;
}

/**
 * League-wide average OVR, recomputed fresh from the live pool on every
 * call — deliberately a function, not a cached constant. Used to be a
 * `LEAGUE_AVERAGE_OVR` constant computed once at module load; that went
 * stale the moment the pool could change (a real off-season run recomputes
 * every player's OVR — see engine/progression.ts's `runOffSeason`), so it's
 * removed rather than left as a trap. Matches the reasoning listNeeds.ts's
 * own doc comment already gave for avoiding exactly this const.
 */
export function leagueAverageOvr(): number {
  return averageOvr(ALL_PLAYERS);
}
